// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgTRWo-IpXko6hnYhx6rEEc82CMTy5bU4',
    appId: '1:536947884270:web:fca027662cb0330ea633ff',
    messagingSenderId: '536947884270',
    projectId: 'project-a2bb2',
    authDomain: 'project-a2bb2.firebaseapp.com',
    storageBucket: 'project-a2bb2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB8dD30ksBgWfalaSrN4FvRC8qnl-jxrY',
    appId: '1:536947884270:android:815ad7c2bdb72283a633ff',
    messagingSenderId: '536947884270',
    projectId: 'project-a2bb2',
    storageBucket: 'project-a2bb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbuzV94FhCeUhSXc3lBxqeKSAoJk2UaQc',
    appId: '1:536947884270:ios:fdbeba62b07f5699a633ff',
    messagingSenderId: '536947884270',
    projectId: 'project-a2bb2',
    storageBucket: 'project-a2bb2.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbuzV94FhCeUhSXc3lBxqeKSAoJk2UaQc',
    appId: '1:536947884270:ios:fdbeba62b07f5699a633ff',
    messagingSenderId: '536947884270',
    projectId: 'project-a2bb2',
    storageBucket: 'project-a2bb2.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgTRWo-IpXko6hnYhx6rEEc82CMTy5bU4',
    appId: '1:536947884270:web:1658e079cbf94a3fa633ff',
    messagingSenderId: '536947884270',
    projectId: 'project-a2bb2',
    authDomain: 'project-a2bb2.firebaseapp.com',
    storageBucket: 'project-a2bb2.firebasestorage.app',
  );
}
