name: project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: 5.5.3
  firebase_core: ^3.13.0
  image_picker: ^1.0.7
  sqlite3: ^2.7.5
  hive: ^2.0.0
  hive_flutter: ^1.1.0
  http: ^0.13.4
  flutter_secure_storage: ^8.0.0
  web_socket_channel: ^2.4.0
  provider: ^6.0.5 
  cached_network_image: ^3.3.0  
  socket_io_client: ^2.0.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.0.0
  connectivity_plus: ^5.0.2
  sqflite: ^2.3.0
  path_provider: ^2.1.2
  gallery_saver: ^2.3.2
  share_plus: ^7.0.1
  uuid: ^4.3.3
  universal_io: ^2.2.0
  universal_html: ^2.2.1
  file_saver: ^0.2.13
  sqflite_common_ffi_web:  ^1.0.0
  js: ^0.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^1.1.3
  build_runner: ^2.3.3
flutter:
  uses-material-design: true
  assets:
    - assets/images/
