name: project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^4.12.0
  firebase_core: ^2.16.0
  image_picker: ^1.0.7
  http: ^0.13.4
  flutter_secure_storage: ^8.0.0
  web_socket_channel: ^2.4.0
  provider: ^6.0.5 
  cached_network_image: ^3.3.0  
  socket_io_client: ^2.0.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
